# Site settings
title: Drunken Sansa, a throwaway repo!
email: your-email@domain.com
description: This is a throwaway repo. The only purpose of it is to get a hang with Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jckr.github.io/drunken-sansa" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
